### PR TITLE
CYP21A2,measurement

### PR DESCRIPTION
**Pull request by pnrobinson**
There is still an issue with the low boundary of the reference range for prolactin (0) not being output, this is likely an issue in pyphetools.
-- no this turned out to be the fact that protobuf does not serialize default values (such as 0 for a float). There are several different ranges for prolactin, and I changed it to low=2 instead of low=0 accordingly.

### CODE REVIEW

**Comment by pnrobinson** [comment]
This is a cohort with Measurements messages for t-test.
The CI has an error that I think is unrelated:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/ppktstore/__main__.py", line 158, in <module>
    sys.exit(main(sys.argv[1:]))
             ^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/ppktstore/__main__.py", line 104, in main
    return qc_phenopackets(
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/ppktstore/release/qc/_impl.py", line [16](https://github.com/monarch-initiative/phenopacket-store/actions/runs/10651865722/job/29524944197?pr=148#step:5:17), in qc_phenopackets
    auditor.audit(
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/ppktstore/release/qc/_checks.py", line 122, in audit
    check.audit(
TypeError: UniqueIdsCheck.audit() got an unexpected keyword argument 'item'
```

**Comment by ielis** [comment]
Yeah, that was my mistake. I deployed a new `phenopacket-store-toolkit` release with a patch and it is OK now.

**Comment by pnrobinson** [comment]
@ielis 
this is the cohort that I think we can use to demonstrate a t test. 
For now, I create HPO terms for numerical measurements that are abnormal, I think this is the most reasonable approach given that some people might use this cohort as a part of a larger analysis with just HPO terms.
I will write some documentation about the t test, but basically, we would want to do one t test for each of the LOINC codes used in the measurements. I am not sure we can completely automate this, but we could do one of two things

1. The user has to enter a list of LOINC codes and we search for measurements for each code
2. We extract all measurements that have numerical values and group them according to the Assay code (LOINC or not) used in the measurement assay field. We then attempt to extract a numerical value from the Value field (Note that we can also have ComplexValues and some other kinds of Measurement, so we probably want to emit a warning or a message about parsing). We then do one t test for each  kind of measurement where we have more than a given number of values.

The second option is probably the one we want (also with MTC). Thoughts?

**Comment by pnrobinson** [comment]
I will merge now for simplicity and add this to the gpsea tracker

**Pull request merged**
